package pcg.talkbackplus;
public enum TalkBackPlusEventType {
    EVENT_NONE,
    EVENT_DOWN,
    EVENT_CENTER_DOUBLE_CLICK,
    EVENT_LEFT_FLING_DOWN,
    EVENT_LEFT_FLING_UP,
    EVENT_LEFT_FLING_RIGHT,
    EVENT_LEFT_FLING_LEFT,
    EVENT_RIGHT_FLING_DOWN,
    EVENT_RIGHT_FLING_UP,
    EVENT_RIGHT_FLING_LEFT,
    EVENT_RIGHT_FLING_RIGHT,
    EVENT_TOP_FLING_LEFT,
    EVENT_TOP_FLING_RIGHT,
    EVENT_BOTTOM_FLING_LEFT,
    EVENT_BOTTOM_FLING_RIGHT,
    EVENT_LEFT_TOP_DOUBLE_CLICK,
    EVENT_LEFT_BOTTOM_DOUBLE_CLICK,
    EVENT_RIGHT_TOP_DOUBLE_CLICK,
    EVENT_RIGHT_BOTTOM_DOUBLE_CLICK,
    EVENT_CENTER_GESTURE_UP,
    EVENT_CENTER_GESTURE_DOWN,
    EVENT_CENTER_GESTURE_LEFT,
    EVENT_CENTER_GESTURE_RIGHT,
    EVENT_CENTER_FLING_DOWN,
    EVENT_CENTER_FLING_UP,
    EVENT_CENTER_FLING_LEFT,
    EVENT_CENTER_FLING_RIGHT,
}
    // 应该会有更多的Event












